# Generated by Django 2.0.4 on 2018-04-17 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.TextField()),
                ('age', models.IntegerField(default=18)),
                ('nick_name', models.CharField(max_length=240)),
                ('rut', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('last_name', models.CharField(max_length=240)),
                ('nick_name', models.CharField(max_length=240)),
                ('age', models.IntegerField(default=18)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('rut', models.CharField(max_length=240)),
                ('height', models.IntegerField(default=170)),
                ('weight', models.IntegerField(default=70)),
                ('mail', models.TextField()),
                ('photo', models.ImageField(upload_to='player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team_description', models.TextField()),
                ('team_img', models.ImageField(upload_to='team')),
                ('team_code', models.CharField(max_length=3)),
            ],
        ),
    ]
