# Generated by Django 2.0.4 on 2018-04-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20180417_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to='MEDIA'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_img',
            field=models.ImageField(upload_to='MEDIA'),
        ),
    ]
