# Generated by Django 2.0.4 on 2018-04-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20180418_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
