# Generated by Django 2.0.4 on 2018-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20180418_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Base', 'Base'), ('Escolta', 'Escolta'), ('Alero', 'Alero'), ('Ala-pivot', 'Ala-pivot'), ('Pivot', 'Pivot')], default='Base', max_length=9),
        ),
    ]
